# objetivo é enviar para o dockerhub
name: CI
# CI é gatilhada depois de uma ação

on:
  push:
    branches:
      - main

jobs:
  build-and-push: 
    name: 'build and push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # gerar tag por rash do commit
    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    # logar no container registry
    - name: login container registry
      uses: docker/login-action@v3
      with: 
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    
    - name: Build docker image
      run: docker build -t albersonaaraujo/nlw-journey-devops:${{steps.generate_sha.outputs.sha}} .

    # enviar imagem